
```{r moving mean}

rm(list=ls())

for(f in seq(4,20,2)){
  for(w in seq(4,20,2)){
print(c(f,w))

load(paste('D:/GitHub/projects/temperatureProject/eWB.RData',sep=''))

siteList <- unique(e$site)
fileSource  <- 'WB'


#below is from temperatureSegemnetedBreakPointAnalysis.Rmd
# grabbed these chunks on 11/19/13 and merged into on big chink to run loops
# graphs are below

#===============================================================================
#Get moving mean and SD of temp index for each site and put into the data frame:
#===============================================================================
window <- w #10 # frame sizefor moving mean, which is centered by default

nSites <- length(siteList)
siteYearCombos <- unique(e[,c('site','year')])
#siteYearCombos$site  <- factor(siteYearCombos$site)

e$movingMean <- NA
e$movingSD <- NA

for (i in 1:nrow(siteYearCombos)){

#  print(c(i,as.character(siteYearCombos$site[i]),siteYearCombos$year[i]))
  
  currSite <- which(e$site == as.character(siteYearCombos$site[i]) & e$year == siteYearCombos$year[i] )

  currMean <-  rollapply(e$tempIndex[currSite], width=window, fill=NA, mean)
  currSD <-    rollapply(e$tempIndex[currSite], width=window, fill=NA, sd)

  e$movingMean[currSite] <- currMean
    e$movingSD[currSite] <- currSD
}

#e <- cbind(e, movingMean=movingMean[2:length(movingMean)], movingSD=movingSD[2:length(movingSD)])

e$meanSDDiff <- e$movingSD - e$movingMean

# just to make sure the merge doens't screw up order
e <- e[order(e$count),]

# look at some raw data

#ggplot( e[e$site == e$site[2] ,], aes(dOY,temp) ) + geom_point() + geom_point(aes(dOY,airTemp),color='red') + facet_grid(site~year)

#table( e$year,e$site,is.na( e$temp ) )



#################################################
# set up breaks df
#################################################

breaks <- data.frame(array(NA,c(nrow(siteYearCombos),7)))
names(breaks) <- c('site','year','springBP','summerBP','fallBP','quantileLo','quantileHi')
breaks$fallBPComplete <- FALSE
breaks$springBPComplete <- FALSE
breaks$springOrFallBPComplete <- FALSE
breaks$summerBPComplete <- FALSE

breaks$quantileLo <- NA
breaks$quantileHi <- NA

beginningDayForCI <- 125
endingDayForCI <- 275
loCI <- 0.001
hiCI <- 0.999


for ( i in 1:nrow(siteYearCombos)){
#  print(i)
  breaks$year[i] <- as.numeric(siteYearCombos$year[i])
  breaks$site[i] <- as.character(siteYearCombos$site[i]) #would like this to stay a factor, but it ends up as numeric in 'breaks'. not sure why
 
  tmp <- e[e$site == siteYearCombos$site[i] & e$year  %in% siteYearCombos$year[i] & e$dOY %in% beginningDayForCI:endingDayForCI,'tempIndex']
  if (any(!is.na(tmp))){
    TIQ <- quantile(tmp, probs=c(loCI,0.5,hiCI),na.rm=T)
    #  movingSDQ <- quantile(e[e$site == siteList[j] & e$year  %in% year & e$dOY %in% beginningDayForCI:endingDayForCI, 'movingSD'], probs=c(0.005,0.5,0.995),na.rm=T)
    
    breaks$quantileLo[i] <- TIQ[1]
    breaks$quantileHi[i] <- TIQ[3]
  
  }
}  



#===================================================================================
#Use runs analysis of the movingMean to define spring and fall breakpoints:
#===================================================================================

minCompleteDOYBP1 <- 15
maxCompleteDOYBP1 <- 175
numForCompleteBP1 <- round( ( maxCompleteDOYBP1-minCompleteDOYBP1 ) * 0.9 )
minCompleteDOYBP3 <- 225
maxCompleteDOYBP3 <- 350
numForCompleteBP3 <- round( ( maxCompleteDOYBP3-minCompleteDOYBP3 ) * 0.9 )

numForward <- f#7 + 0 #number of days in a row that need to be within the CIs to get assigned synchronised


for (j in 1:nSites){
  
  curSite <- which(e$site == siteList[j])
  e1 <- e[curSite,]

	e3Spring <- e1[ e1$dOY >= minCompleteDOYBP1 & e1$dOY <= maxCompleteDOYBP1, ]
	
	completeYearsSpring <- NULL #empty out from previous run
  
  if ( !empty( e3Spring ) ) {  #in case e3Spring is empty - avoids error
	  completeSpring <- as.data.frame( table( e3Spring$year,is.na( e3Spring$temp ) ) )
	  incompleteYearsSpring <- as.numeric(as.character(completeSpring$Var1[completeSpring$Var2 == 'FALSE' & completeSpring$Freq <  numForCompleteBP1]))
	  completeYearsSpring <-   as.numeric(as.character(completeSpring$Var1[completeSpring$Var2 == 'FALSE' & completeSpring$Freq >= numForCompleteBP1]))
  }
  
	e3Fall <- e1[ e1$dOY >= minCompleteDOYBP3 & e1$dOY <= maxCompleteDOYBP3, ]
	
  completeYearsFall <- NULL
	
	if ( !empty( e3Fall ) ) {
	  completeFall <- as.data.frame( table( e3Fall$year,is.na( e3Fall$temp ) ) )
	  incompleteYearsFall <- as.numeric(as.character(completeFall$Var1[completeFall$Var2 == 'FALSE' & completeFall$Freq <  numForCompleteBP3]))
	  completeYearsFall <-   as.numeric(as.character(completeFall$Var1[completeFall$Var2 == 'FALSE' & completeFall$Freq >= numForCompleteBP3]))
	} 
  
	completeYearsSpringOrFall <- unique(c(completeYearsSpring,completeYearsFall))
	#quantiles <- data.frame(year=c(min(e1$year):max(e1$year)))
	#quantiles$lo <- NA
	#quantiles$hi <- NA 
	
	for (year in completeYearsSpringOrFall){ 

	  breaks$springOrFallBPComplete[ breaks$year == year & breaks$site == siteList[j] ] <- TRUE
#	  print(c('BP 1 and 3',j,as.character(siteList[j]),year))
 
    lo <- breaks$quantileLo[breaks$year == year & breaks$site == siteList[j]] 
    hi <- breaks$quantileHi[breaks$year == year & breaks$site == siteList[j]] 
    
		runs <- data.frame(array(NA,c(1,numForward)))
		eYear <- e1[e1$year == year, ] 

		if(year %in% completeYearsSpring){
			
			#out <- segmented( lm(temp~dOY, data=e1[e1$year == year,]), seg.Z=~dOY, psi=list(dOY=c(100,200)))
			#tryCatch({out <- segmented( lm(temp~dOY, data=e1[e1$year == year,]), seg.Z=~dOY, psi=list(dOY=c(100,200)))},error=function(e){cat("ERROR :",conditionMessage(e), "\n")})

			# time forward until approx breakpoint ascending/descending water temp (in 'breaks')
			for (i in 1:(200)){ #-window*winFactor )){
				for (ii in 2:numForward ){
          
          if( (i+ii-2) %in% eYear$dOY ) {   # amke sure that the dOY is in the looping variable      
			  	  runs[ i,ii ] <- 1*((eYear$movingMean[ eYear$dOY == (i+ii-2) ] >= lo) & (eYear$movingMean[ eYear$dOY == (i+ii-2) ] <= hi))
          } else
            runs[ i,ii ] <- 1  

				}
				runs[ i,1 ] <- prod( runs[ i, 2:numForward ] )
			}
			breaks$springBP[ breaks$year == year & breaks$site == siteList[j] ] <- min(which(runs[,1] == 1))
			breaks$springBPComplete[ breaks$year == year & breaks$site == siteList[j] ] <- TRUE
		}
      
	 if(year %in% completeYearsFall){
			# Make this not arbitrary
			# time backward until approx breakpoint ascending/descending water temp (in 'breaks')
	   stopLoop <- max( c( minCompleteDOYBP3,min(eYear$dOY)+numForward + 1 ) )  # to keep from going past lower limit if dOY
			for (i in  max(eYear$dOY):stopLoop){
				for (ii in 2:numForward ){
          
				  if( (i-ii+2) %in% eYear$dOY ) { 
					  runs[ i,ii ] <- 1*((eYear$movingMean[ eYear$dOY == (i-ii+2) ] >= lo) & (eYear$movingMean[ eYear$dOY == (i-ii+2) ] <= hi))
				  } else
				    runs[ i,ii ] <- 1 
				}
				runs[ i,1 ] <- prod( runs[ i, 2:numForward ] )
			}
			breaks$fallBP[ breaks$year == year & breaks$site == siteList[j] ] <- max(which(runs[,1] == 1))
			breaks$fallBPComplete[ breaks$year == year & breaks$site == siteList[j] ] <- TRUE
		}			
			
#		} #completeYears loop
	} #year loop
} #site loop

# add in means for missing BP. use the xBPWMean below to constrain the date range for estimating BP 2 
meanBP <- ddply( breaks, .(site), summarise, meanSpringBP = mean(springBP,na.rm=T), meanFallBP = mean(fallBP,na.rm=T) )
breaks$meanSpringBP <- NULL; breaks$meanFallBP <- NULL # in case we've merged before

breaks <- merge( x=breaks, y= meanBP, all.x=T, by=c('site') )

breaks$springBPWMean <- ifelse( is.na(breaks$springBP), breaks$meanSpringBP, breaks$springBP )
breaks$springBPWMean <- ifelse( !is.finite(breaks$springBPWMean), mean(breaks$meanSpringBP[is.finite(breaks$meanSpringBP)]), breaks$springBPWMean )

breaks$fallBPWMean <- ifelse( is.na(breaks$fallBP), breaks$meanFallBP, breaks$fallBP )
breaks$fallBPWMean <- ifelse( !is.finite(breaks$fallBPWMean), mean(breaks$meanFallBP[is.finite(breaks$meanFallBP)]), breaks$fallBPWMean )

# can have empty breakPoints if don't calculate a mean across years for each site in the ddply above
# i.e. only data for one year in a site or no years have data before the spring cutoff or after the fall cutoff
# in this case, just fill in the cutoffs, so the summer breakPoint can be calculated
breaks$springBPWMean[is.na(breaks$springBPWMean )] <- minCompleteDOYBP1
breaks$fallBPWMean[is.na(breaks$fallBPWMean )] <- maxCompleteDOYBP3


#====================================================================================================================
#Segmented regression of water temperature to get breakpoint between ascending and descending temps by year and site:
# summerBP or BP 2
# can get bad bp2 estimates when water temp increases very rapidly in the spring. as of 11/15/13, including the middle 90% of the datapts between bp1 and bp3 to trim the ends 
#====================================================================================================================
minCompleteDOYBP2 <- 180
maxCompleteDOYBP2 <- 240
numForCompleteBP2 <- round( ( maxCompleteDOYBP2-minCompleteDOYBP2 ) * 0.75 ) #changed from 0.9

trimProp <- 0.05 # the proportion of obs btw bp1 and bp3 to trim for segmented

segDF <- data.frame(site=NA,year=NA,dOY=NA,temp=NA,pred=NA)

for (j in 1:nSites){
  #  for (j in 1:10){
  
  curSite <- which(e$site == siteList[j])
  e1 <- e[curSite,]
  
  #are data complete for a year?
  
  e3 <- e1[ e1$dOY >= minCompleteDOYBP2 & e1$dOY <= maxCompleteDOYBP2, ]
  
  if(nrow(e3) > 0) {
    complete <- as.data.frame( table( e3$year,is.na( e3$temp ) ) )
    incompleteYears <- as.numeric(as.character(complete$Var1[complete$Var2 == 'FALSE' & complete$Freq <  numForCompleteBP2]))
    completeYears <-   as.numeric(as.character(complete$Var1[complete$Var2 == 'FALSE' & complete$Freq >= numForCompleteBP2]))
  }
  if(nrow(e3) == 0) completeYears <- NULL #skip the loops if no data
    
  for (year in completeYears){

 #     print(c('BP2',j,as.character(siteList[j]),year))
      
      bp1 <- breaks$springBPWMean[breaks$site == siteList[j] & breaks$year == year ]
      bp3 <- breaks$fallBPWMean[breaks$site == siteList[j] & breaks$year == year ]
      
      trim <- round((bp3-bp1) * trimProp)
      minDOY <- bp1 + trim
      maxDOY <- bp3 - trim
      
      if(exists('out')) rm(out) 
      dat <- e1[e1$year == year & e1$dOY >= minDOY & e1$dOY <= maxDOY,]
      tryCatch({out <- segmented( lm(temp~dOY, data=dat), 
                                  seg.Z=~dOY, psi=list(dOY=c(200)))},error=function(e){cat("ERROR :",conditionMessage(e), "\n")})      
      
      if(exists('out')){
        
        # commented this out because it was in here before bp2 seg regression was done only between bp1 and bp3
        #if ( summary(out)$coefficients[2] < 0 ){  
        #  rm(out) #Delete segmented regression if slope of segment 1 is negative 
        
          # for making seg regression graphs in ggplot          
          segDF <- rbind( segDF, cbind(site=siteList[j],year=year,dOY=dat$dOY,temp=dat$temp,pred=out$fitted.values) )
          
          #Add back in trimmed data - these are btw bp1 and bp3 but were not used in the seg regression for bp2
          ## decided not to do this, makes the seg2 two graph misleading. ##
#          datBeforeTrim <- e1[e1$year == year & e1$dOY >= bp1 & e1$dOY <= minDOY,]
#          if(nrow(datBeforeTrim) > 0) segDF <- rbind( segDF, cbind(site=siteList[j],year=year,dOY=datBeforeTrim$dOY,temp=datBeforeTrim$temp,pred=NA) )
          
#          datAfterTrim <- e1[e1$year == year & e1$dOY <= bp3  & e1$dOY >= maxDOY,]
#          if(nrow(datAfterTrim) > 0) segDF <- rbind( segDF, cbind(site=siteList[j],year=year,dOY=datAfterTrim$dOY,temp=datAfterTrim$temp,pred=NA) )
        #}
      }
      png(filename=paste0(getwd(),"/figs/summerBP/summerBP_",e1$site[1],"_",year,".png"),width=1000, height=600, bg="white")
      plot(e1$dOY[e1$year %in% year], e1$temp[e1$year %in% year],ylim=c(-5,25),xlim=c(0,366))
      
      if(exists("out")){
        
        breaks$summerBP[breaks$year == year & breaks$site == siteList[j]] <- summary(out)$psi[1,2]
        breaks$summerBPComplete[breaks$year == year & breaks$site == siteList[j]]  <- TRUE
        
        plot(out,add=T,link=FALSE,lwd=2,col=2:3, lty=c(1),ylim=c(-5,25),xlim=c(0,366))
        lines(out,col=2,pch=19,bottom=FALSE,lwd=2) 
        
      }
      title(main=paste(e1$site[1],"_",year))
      dev.off()
      #
  }

}

# for WB MS graphs
if( fileSource == 'WB') segDF$site <- factor(segDF$site,levels=1:4, labels=c('WB JIMMY','WB MITCHELL','WB OBEAR','WEST BROOK'))

# add in means for summer BP. used when  have a fall but no spring or summer BP and there are data in the spring
meanBP2 <- ddply( breaks, .(site), summarise, meanSummerBP = mean(summerBP,na.rm=T) )
breaks$meanSummerBP <- NULL # in case we've merged before

breaks <- merge( x=breaks, y= meanBP2, all.x=T, by=c('site') )

breaks$summerBPWMean <- ifelse( is.na(breaks$summerBP), breaks$meanSummerBP, breaks$summerBP )
breaks$summerBPWMean <- ifelse( !is.finite(breaks$summerBPWMean), mean(breaks$meanSummerBP[is.finite(breaks$meanSummerBP)]), breaks$summerBPWMean )

#----------------------------------------------------------------
#Merge the breakpoints and quantiles with the existing dataframe:
#----------------------------------------------------------------
#et <- merge( x=e, y=breaks, by.x=c('year','site'),by.y=c('year','site'),all.x=T)
et <- merge( x=e, y=breaks, by=c('year','site'),all.x=T)

# need to sort for plotting pred
segDF <- segDF[order(segDF$site,segDF$year,segDF$dOY),]

if(exists("breaksOut")) breaksOut <- rbind(breaksOut,cbind(w,f,breaks))
if(!exists("breaksOut")) breaksOut <- cbind(w,f,breaks)


 }
}

save(breaksOut,file='D:/GitHub/projects/temperatureProject/breaksOut.RData')

```

```{r graphs}
bpO <- melt(breaksOut[,1:7], id.vars=1:4)
bpO$siteYear <- paste(bpO$site,bpO$year)
bpO$vw <- paste(bpO$variable,bpO$w)

ggplot(bpO[bpO$site=='WEST BROOK' &bpO$year %in% 2003,],#2002:2011,], 
#ggplot(bpO[bpO$year <2012,],        
       aes( f,value, group=factor(vw) ))+
  geom_point(aes(color=factor(w),shape=factor(w)),size=7)+
  geom_line(aes(color=factor(w)))+ 
  facet_grid(site~year)

library(directlabels)

g <- 
  ggplot(bpO[bpO$site=='WEST BROOK' & bpO$year %in% 2002:2006,],#2002:2011,], 
  aes(x=f,y=w,z=value)) +
#    geom_tile(aes(fill = value))+
  geom_contour(aes(colour = ..level..))+
  geom_text(aes(label=value))+
  facet_grid(year~variable)#,scales='free_x')+
#geom_dl(aes(label=variable),method="last.points")
direct.label(g)

```

